name: Node 10 -- install packages with YARN

on: [push]

jobs:
  github:
    runs-on: ubuntu-latest    
    steps:
      - uses: actions/checkout@v1

      - name: Build :lastest
        run: docker build -f tests/build-on-docker/node10WithYarn.Dockerfile .
